# Copyright (c) 2021 Regents of the University of California
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

{% set name = "tsnecuda" %}
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: ../../

build:
    number: {{ number }}

outputs:
  - name: tsnecuda
    build:
      string: "h{{ PKG_HASH }}_{{ number }}_cuda{{ cudatoolkit }}"
    requirements:
      build:
        - {{ compiler('cxx') }}
        - libxml2 # Note: This is a weird bug with cudatoolkit-dev, where if libxml2 isn't present in the build
                  # environment, it won't post-link correctly in the host environment.
      host:
        - python {{ python }}
        - cmake >=3.20
        - mkl-devel >=2018
        - blas =*=mkl
        - cudatoolkit-dev {{ cudatoolkit }}
        - cudatoolkit {{ cudatoolkit }}
        - faiss-gpu ==1.6.5
        - gflags
        - gtest
        - gmock
      run:
        - mkl >=2018
        - blas =*=mkl
        - faiss-gpu ==1.6.5
        - numpy >=1.14
        - {{ pin_compatible('python') }}
        - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    test:
      imports:
        - tsnecuda
        - tsnecuda.TSNE

about:
  home: https://github.com/CannyLab/tsne-cuda
  license: LICENSE.txt
  license_family: BSD
  license_file: ''
  summary: CUDA Implementation of T-SNE with Python bindings
  description: "===========\ntsnecuda\n===========\n\ntsnecuda provides an optimized CUDA implementation of the T-SNE algorithm by L Van der Maaten. tsnecuda is able to compute the T-SNE of large numbers\
    \ of points up to 1200 times faster than other leading libraries, and provides simple python bindings with a SKLearn style interface::\n\n    #!/usr/bin/env python\n\n    from tsnecuda import TSNE\n\
    \    embeddedX = TSNE(n_components=2).fit_transform(X)\n\nFor more information, check out the repository at https://github.com/rmrao/tsne-cuda. \n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers:
    - DavidMChan
